blank_issues_enabled: false
contact_links:
  - name: Github Discussions:
    url: https://github.com/orgs/EvilSpaceGoblins/discussions
    about: Please ask and answer questions here.
  - name: Discord
    url: https://bounty.github.com/
    about: Get in contact with us.
