name: "Feature Request 🚀"
description: "Ask for a new feature."
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request form!
        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Discord Handle, Github Handle etc.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Feature Description
      description: Provide a detailed description of the feature you want or need.
    validations:
      required: true
